version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8181:8181
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8181 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
