version: '3.8'

services:
  app:
    build: .
    networks:
      - caddy
    labels:
      caddy: radcalc.app
      caddy.reverse_proxy: "{{upstreams 8181}}"
    restart: unless-stopped

networks:
  caddy:
    external: true